/**
 * Phase 1: pull the shared site chrome out of the per-page components.
 *
 * Every converted page has the same skeleton:
 *
 *   <div className="page-wrapper">
 *     ...preloader / back-to-top / cursors / offcanvas...   <- chrome
 *     <header>...</header>                                  <- header
 *     <div id="smooth-wrapper"><div id="smooth-content">     <- GSAP ScrollSmoother
 *       ...page content...                                  <- the only per-page part
 *       <footer>...</footer>                                <- footer
 *     </div></div>
 *   </div>
 *
 * The chrome/header/footer become shared components rendered by a layout, and
 * each page component keeps only the content. The ScrollSmoother wrapper must
 * stay in this exact nesting or GSAP's smooth scrolling breaks.
 */

const PAGE_WRAPPER = '<div className="page-wrapper">';
const SMOOTH_CONTENT = '<div id="smooth-content">';

function between(src, startMarker, endMarker, { inclusive = false } = {}) {
  const i = src.indexOf(startMarker);
  const j = src.indexOf(endMarker, i);
  if (i === -1 || j === -1) throw new Error(`markers not found: ${startMarker} .. ${endMarker}`);
  return inclusive ? src.slice(i, j + endMarker.length) : src.slice(i + startMarker.length, j);
}

/** Chrome = everything between the page wrapper and the <header> tag. */
export function extractChrome(src) {
  return between(src, PAGE_WRAPPER, "<header ").trimEnd();
}

export function extractHeader(src) {
  return between(src, "<header ", "</header>", { inclusive: true });
}

export function extractFooter(src) {
  return between(src, "<footer ", "</footer>", { inclusive: true });
}

/** The per-page part: inside #smooth-content, before the footer. */
export function extractContent(src) {
  const body = between(src, SMOOTH_CONTENT, "<footer ");
  // Drop the trailing `{/* Footer Start */}` comment that belonged to the footer.
  return body.replace(/\s*\{\/\*[^*]*Footer[^*]*\*\/\}\s*$/, "\n");
}

import { IMAGE_IMPORT, backgroundify, imagify } from "./imagify.mjs";
import { LINK_IMPORT, linkify } from "./linkify.mjs";

/** Shared across every render so ~500 image headers are read once. */
const dimCache = new Map();

const INDENT = /^/gm;
const reindent = (s, pad) => s.replace(INDENT, pad).replace(/^\s+$/gm, "");

export function renderChromeComponent(chrome) {
  const linked = linkify(chrome);
  const img = imagify(linked.code, dimCache);
  const code = img.code;
  const count = linked.count;
  const imgCount = img.count;
  return `/* Generated by scripts/extract-chrome.mjs — do not hand-edit. */
${[count ? LINK_IMPORT : "", imgCount ? IMAGE_IMPORT : ""].filter(Boolean).join("\n")}${count || imgCount ? "\n" : ""}
/** Preloader, back-to-top button, custom cursor and the offcanvas mobile menu. */
export default function SiteChrome() {
  return (
    <>
${reindent(code.trim(), "      ")}
    </>
  );
}
`;
}

export function renderHeaderComponent(header) {
  const linked = linkify(header);
  const img = imagify(linked.code, dimCache);
  // The logo is the first image painted on every page — never lazy-load it.
  const code = img.code.replace("<Image ", "<Image priority ");
  const count = linked.count;
  const imgCount = img.count;
  return `/* Generated by scripts/extract-chrome.mjs — do not hand-edit. */
${[count ? LINK_IMPORT : "", imgCount ? IMAGE_IMPORT : ""].filter(Boolean).join("\n")}${count || imgCount ? "\n" : ""}
/** Shared site header (the template's header-section-2 layout). */
export default function SiteHeader() {
  return (
${reindent(code.trim(), "    ")}
  );
}
`;
}

export function renderFooterComponent(footer) {
  // The template varies only the bottom-padding utility per page, so expose it.
  const parametrised = footer.replace(
    /<footer className="([^"]*?)\s*footer-fix-padding-\d+\s*"/,
    '<footer className={`$1 ${paddingClass}`}',
  );
  if (parametrised === footer) throw new Error("footer padding class not found");
  const linked = linkify(parametrised);
  const img = imagify(linked.code, dimCache);
  const code = img.code;
  const count = linked.count;
  const imgCount = img.count;
  return `/* Generated by scripts/extract-chrome.mjs — do not hand-edit. */
${[count ? LINK_IMPORT : "", imgCount ? IMAGE_IMPORT : ""].filter(Boolean).join("\n")}${count || imgCount ? "\n" : ""}
/**
 * Shared site footer. \`paddingClass\` reserves room for the CTA section that
 * overlaps the footer, and differs between the home page and inner pages.
 */
export default function SiteFooter({
  paddingClass = "footer-fix-padding-7",
}: {
  paddingClass?: string;
}) {
  return (
${reindent(code.trim(), "    ")}
  );
}
`;
}

export function renderShellComponent() {
  return `/* Generated by scripts/extract-chrome.mjs — do not hand-edit. */
import SiteChrome from "./site-chrome";
import SiteHeader from "./site-header";
import SiteFooter from "./site-footer";

/**
 * The markup every page shares. #smooth-wrapper/#smooth-content must stay in
 * this exact nesting — GSAP ScrollSmoother targets them by id.
 */
export default function SiteShell({
  children,
  footerPadding,
}: {
  children: React.ReactNode;
  footerPadding?: string;
}) {
  return (
    <div className="page-wrapper">
      <SiteChrome />
      <SiteHeader />
      <div id="smooth-wrapper">
        <div id="smooth-content">
          {children}
          <SiteFooter paddingClass={footerPadding} />
        </div>
      </div>
    </div>
  );
}
`;
}

export function renderPageComponent(name, exportName, content, srcHtml, imports = []) {
  const head = imports.length ? imports.join("\n") + "\n\n" : "";
  return `/* Auto-converted from ${srcHtml} by scripts/html2jsx.mjs — do not hand-edit, re-run the script */
${head}export default function ${exportName}() {
  return (
    <>
${content.trimEnd()}
    </>
  );
}
`;
}
